services:
  tactile_insertion:
    build: .
    image: tactile_insertion:latest
    container_name: tactile_insertion_container
    privileged: true
    devices:
      - /dev/input:/dev/input
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu, utility, compute, graphics, display ]

    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.docker.xauth
      - MUJOCO_GL=egl
      - MUJOCO_EGL_DEVICE_ID=0
      - __GLVND_EXPOSE_LIBGLX=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
      - PYTHONPATH=/app:/app/env_setup:/app/fots_sim:/app/fots_sim/utils:/app/scripts
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY}:/tmp/.docker.xauth:ro

    network_mode: "host"
    ipc: "host"
    tty: true
    stdin_open: true
    command: /bin/bash
