wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.20
    cli_version: 0.24.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1778049675
    t:
      1:
      - 1
      - 41
      2:
      - 1
      - 41
      3:
      - 2
      - 4
      - 13
      - 37
      - 42
      - 61
      4: 3.8.20
      5: 0.24.2
      13: linux-x86_64
    e:
      4z8xta8h2ylnbdjxlk2te2nzvb3vp9j9:
        os: Linux-4.18.0-553.89.1.el8_10.x86_64-x86_64-with-glibc2.17
        python: CPython 3.8.20
        started_at: '2026-05-06T06:41:11.646895Z'
        args:
        - --config
        - /tmp/bc_rnn_19219503.json
        program: robomimic/scripts/train.py
        code_path: robomimic/scripts/train.py
        code_path_local: robomimic/scripts/train.py
        git:
          remote_url: https://github.com/ARISE-Initiative/robomimic.git
          commit: 2804dd97dd1625ec861298a35cb677129d3bfacc
        root: /scratch/zt1/project/enpm690/user/tsadaria/robomimic/wandb
        host: gpu-b9-7.zaratan.umd.edu
        executable: /scratch/zt1/project/enpm690/user/tsadaria/miniconda3/envs/robomimic_venv/bin/python
        cpu_count: 128
        cpu_count_logical: 128
        gpu_type: NVIDIA A100-SXM4-40GB
        gpu_count: 1
        disk:
          /:
            total: '33501757440'
            used: '10187558912'
        memory:
          total: '540064681984'
        gpu_nvidia:
        - name: NVIDIA A100-SXM4-40GB
          memory_total: '42949672960'
          cuda_cores: 6912
          architecture: Ampere
          uuid: GPU-1f94b007-e1a2-f16e-2cc9-46b5bbd5d69b
        cuda_version: '13.1'
        slurm:
          tres_per_task: cpu=16
          nprocs: '1'
          job_name: bc_rnn_fots
          job_qos: normal
          topology_addr: top.b8cef60300d55b46.gpu-b9-7
          tasks_per_node: '1'
          conf: /etc/slurm/slurm.conf
          gtids: '0'
          cpus_on_node: '16'
          oom_kill_step: '0'
          task_pid: '4117876'
          job_user: tsadaria
          nnodes: '1'
          nodeid: '0'
          job_partition: gpu-a100
          cluster_name: zaratan
          job_cpus_per_node: '16'
          job_end_time: '1778114224'
          nodelist: gpu-b9-7
          job_start_time: '1778049424'
          job_num_nodes: '1'
          gpus_on_node: '1'
          procid: '0'
          jobid: '19219503'
          mem_per_node: '65536'
          job_id: '19219503'
          job_account: enpm690-class
          job_uid: '448864'
          submit_host: login-1.zaratan.umd.edu
          submit_dir: /scratch/zt1/project/enpm690/user/tsadaria/robomimic
          topology_addr_pattern: switch.switch.node
          job_gid: '102715'
          ntasks: '1'
          job_nodelist: gpu-b9-7
          job_gpus: '0'
          localid: '0'
          cpus_per_task: '16'
          prio_process: '0'
        writer_id: 4z8xta8h2ylnbdjxlk2te2nzvb3vp9j9
